#include "/Engine/Public/Platform.ush"

RWTexture2D<float4> RenderTarget;
Buffer<float> DrawDesc;

[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void IComputerShader(uint3 DispatchThreadId : SV_DispatchThreadID)
{
    uint width = (uint)DrawDesc[0];
    uint height = (uint)DrawDesc[1];

    if (DispatchThreadId.x >= width || DispatchThreadId.y >= height)
    {
        return;
    }

    RenderTarget[DispatchThreadId.xy] = float4(1.0, 0.0, 0.0, 1.0);
}
